#!/bin/sh
# Start/stop the cron daemon.

test -f /usr/sbin/cron || exit 0

case "$1" in
start)	echo -n "Starting periodic command scheduler: cron"
        start-stop-daemon --start --quiet --exec /usr/sbin/cron
        echo "." 
	;;
stop)	echo -n "Stopping periodic command scheduler: cron"
        start-stop-daemon --stop --quiet --exec /usr/sbin/cron
        echo "."
        ;;
*)	echo "Usage: /etc/init.d/cron start|stop"; exit 1 
        ;;
esac
exit 0
