#!/bin/sh
set -e

update-rc.d cron defaults 89 11 >/dev/null
# Copy existing allow/deny files
crondir="/var/spool/cron"
pausemessage="F"
for fname in allow deny ; do
    if [ -f $crondir/$fname ] ; then
	if [ ! -f $/etc/cron.$fname ] ; then
	    mv $crondir/$fname /etc/cron.$fname
	    echo " "
	    echo "Moving $crondir/$fname to /etc/cron.$fname to comply with Debian policy"
	    pausemessage="T"
	else
	    echo " "
	    echo "Warning:"
	    echo "Both $crondir/$fname and /etc/cron.$fname exist -- cron will"
	    echo "use /etc/cron.$fname"
	    pausemessage="T"
	fi
    fi
done
#
# Move dpkg status file backups, if necessary/possible.
#
( cd /var/lib/dpkg ;
for oldstat in status.yesterday.* ; do
    if [ -f $oldstat ] ; then
        newstat=`echo $oldstat | sed 's/yesterday\.//'`;
        newstat=/var/backups/dpkg.$newstat;            
        if [ ! -f $newstat ] ; then
            mv $oldstat $newstat ;
        fi
    fi                        
done)

if [ -x /etc/init.d/cron ]; then
	if [ -x /usr/sbin/invoke-rc.d ] ; then
	       invoke-rc.d cron start
	else
	       /etc/init.d/cron start
	fi
fi

#DEBHELPER#
