#!/bin/sh
set -e

crondir="/var/spool/cron"
pausemessage="F"
for fname in allow deny ; do
    if [ -f $crondir/$fname ] ; then
	if [ ! -f $/etc/cron.$fname ] ; then
	    mv $crondir/$fname /etc/cron.$fname
	    echo " "
	    echo "Moving $crondir/$fname to /etc/cron.$fname to comply with Debian policy"
	    pausemessage="T"
	else
	    echo " "
	    echo "Warning:"
	    echo "Both $crondir/$fname and /etc/cron.$fname exist -- cron will"
	    echo "use /etc/cron.$fname"
	    pausemessage="T"
	fi
    fi
done

# Add group for crontabs
getent group crontab > /dev/null 2>&1 || addgroup --system crontab

# Fixup crontab binary, directory and files for new group 'crontab'.

if ! dpkg-statoverride --list /usr/bin/crontab > /dev/null ; then
    dpkg-statoverride --update --add root crontab 2755 /usr/bin/crontab
fi

# Can't use dpkg-statoverride for this because it doesn't cooperate nicely
# with cron alternatives such as bcron
chown root:crontab $crondir/crontabs
chmod 1730 $crondir/crontabs

# This used to be done conditionally. It has been disabled to suit cron
# alternative such as bcron. 
cd $crondir/crontabs
set +e
ls -1 |  xargs -r -n 1 --replace=xxx  chown 'xxx:crontab' 'xxx'
set -e
ls -1 | xargs chmod 600

#DEBHELPER#
