#!/bin/sh
set -e
if [ $1 = purge ]; then 
    update-rc.d cron remove >/dev/null
    rm -f /etc/cron.allow /etc/cron.deny
fi
if [ -x /usr/sbin/suidunregister ]; then
	suidunregister -s cron /usr/bin/crontab
fi
