#!/bin/sh
set -e

if [ remove = "$1" ]; then
    dpkg-divert --package cron-se --remove --rename \
        --divert /usr/sbin/cron.cron /usr/sbin/cron
    dpkg-divert --package cron-se --remove --rename \
        --divert /usr/bin/crontab.cron /usr/bin/crontab
fi

# Restart non-se cron
if [ -x /etc/init.d/cron ]; then
	if [ -x /usr/sbin/invoke-rc.d ] ; then
	       invoke-rc.d cron restart
	else
	       /etc/init.d/cron restart
	fi
fi

#DEBHELPER#
